#!/bin/sh

XVFB=/usr/bin/Xvfb
#XVFBARGS=":21 -screen 0 1280x1024x24 -extension RANDR -fbdir /var/run -ac"
XVFBARGS=":21 -screen 0 1280x1024x24 -fbdir /var/run -ac"
PIDFILE=/var/run/xvfb.pid
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/

case "$1" in
  start)
    echo -n "Starting virtual X frame buffer: Xvfb"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping virtual X frame buffer: Xvfb"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
        echo "Usage: /etc/init.d/xvfb {start|stop|restart}"
        exit 1
esac

exit 0
